baseurl = "https://fabienleite.github.io/" 
title = "Fabien Leite"
theme = "coder-portfolio"
languagecode = "en" 
defaultcontentlanguage = "en" 

paginate = 20 

pygmentsstyle = "b2"
pygmentscodefences = true 
pygmentscodefencesguesssyntax = true
pygmentsUseClasses = true 

[params]
    author = "Fabien Leite" 
    info = "Application Security Engineer & Software Crafter" 
    description = "Fabien Leite - Application security engineer"
    keywords = "security,development"
    avatarurl = "images/portrait.jpg"

    # Whether you want to hide copyright and credits in the footer.
    hideCredits = false
    hideCopyright = true

    # Custom CSS
    custom_css = ["css/custom.css"]

    # Alignment of Mobile Menu items
    itemscentered = true

    # RTL support
    rtl = false

    # Bottom sns share
    snsShare = true # new add
    # Popular sns share
    # if you want add sns. please message!
    enableTwitterShare = false  # new add
    enableFacebookShare = false # new add
    enableHatenaShare = false   # new add
    enableLineShare = false     # new add
    enableLinkedInShare = false # new add

    thumbnail = "images/tn.png" # default sns thumbnail

    # Multilanguage mode
    langseparator = "|" # Separates menus from language selectors when site is multilingual.

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/fabienleite/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 2
    url = "https://twitter.com/FabienLeite"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/fabien-leite/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "https://blog.octo.com/author/fabien.leite/"
[[menu.main]]
    name = "{}"
    weight = 1
    url  = "https://github.com/fabienleite/fabienleite.github.io/"
